packages:
  - 'apps/*'
  - 'packages/*'
  - 'client/web'
  - 'client/shared'
  - 'client/web/plugins/**'
  - 'client/packages/**'
  - 'server'
  - 'server/admin'
  - 'server/packages/**'
  - 'server/plugins/**'
  - 'server/test/demo/**'
  - 'website'
allowBuilds:
  b: true
  d: true
  e: true
  i: true
  l: true
  s: true
  u: true
